version: "3.9"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  charts:
    build: ./charts
    container_name: charts_container
    ports:
      - "3000:3000"
    volumes:
      - ./charts:/app
  