steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run_flex_template'
    args: [
      'dataflow', 'flex-template', 'run', 'pipeline',
      '--template-file-gcs-location', 'gs://crypto-trading-v2-dataflow/pipeline.json',
      '--parameters', 'write_dest=bigquery'
    ]
